"""Add inferred_csi field to interaction_analyses

Revision ID: 15bad82d620e
Revises: 6763666040d9
Create Date: 2025-09-17 10:16:56.389561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bad82d620e'
down_revision: Union[str, Sequence[str], None] = '6763666040d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_analyses', sa.Column('inferred_csi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_analyses', 'inferred_csi')
    # ### end Alembic commands ###
