"""Add customer name and job metrics

Revision ID: 272990069489
Revises: 1c8a99405bc1
Create Date: 2025-08-28 14:22:56.801809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '272990069489'
down_revision: Union[str, Sequence[str], None] = '1c8a99405bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_upload_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_conversations_fb_chat_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('idx_conversation_date'), table_name='daily_analyses')
    op.drop_index(op.f('ix_daily_analyses_csi_score'), table_name='daily_analyses')
    op.drop_index(op.f('ix_daily_analyses_id'), table_name='daily_analyses')
    op.drop_table('daily_analyses')
    op.drop_index(op.f('idx_fb_chat_direction'), table_name='messages')
    op.drop_index(op.f('idx_social_create_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_fb_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_processed_chats_fb_chat_id'), table_name='processed_chats')
    op.drop_index(op.f('ix_processed_chats_id'), table_name='processed_chats')
    op.drop_table('processed_chats')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_table('job_daily_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_daily_analyses',
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('daily_analysis_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['daily_analysis_id'], ['daily_analyses.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'daily_analysis_id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('metric_name', sa.VARCHAR(), nullable=False),
    sa.Column('metric_value', sa.FLOAT(), nullable=False),
    sa.Column('metric_metadata', sqlite.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=1)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_table('processed_chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fb_chat_id', sa.VARCHAR(), nullable=False),
    sa.Column('processed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('message_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_chats_id'), 'processed_chats', ['id'], unique=False)
    op.create_index(op.f('ix_processed_chats_fb_chat_id'), 'processed_chats', ['fb_chat_id'], unique=1)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fb_chat_id', sa.VARCHAR(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=True),
    sa.Column('message_content', sa.TEXT(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('social_create_time', sa.DATETIME(), nullable=False),
    sa.Column('agent_info', sqlite.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('sentiment_confidence', sa.FLOAT(), nullable=True),
    sa.Column('topics', sqlite.JSON(), nullable=True),
    sa.Column('is_first_contact', sa.BOOLEAN(), nullable=True),
    sa.Column('response_time_minutes', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_fb_chat_id'), 'messages', ['fb_chat_id'], unique=False)
    op.create_index(op.f('idx_social_create_time'), 'messages', ['social_create_time'], unique=False)
    op.create_index(op.f('idx_fb_chat_direction'), 'messages', ['fb_chat_id', 'direction'], unique=False)
    op.create_table('daily_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_date', sa.DATETIME(), nullable=False),
    sa.Column('sentiment_score', sa.FLOAT(), nullable=True),
    sa.Column('sentiment_shift', sa.FLOAT(), nullable=True),
    sa.Column('resolution_achieved', sa.FLOAT(), nullable=True),
    sa.Column('fcr_score', sa.FLOAT(), nullable=True),
    sa.Column('ces', sa.FLOAT(), nullable=True),
    sa.Column('first_response_time', sa.FLOAT(), nullable=True),
    sa.Column('avg_response_time', sa.FLOAT(), nullable=True),
    sa.Column('total_handling_time', sa.FLOAT(), nullable=True),
    sa.Column('effectiveness_score', sa.FLOAT(), nullable=True),
    sa.Column('effort_score', sa.FLOAT(), nullable=True),
    sa.Column('efficiency_score', sa.FLOAT(), nullable=True),
    sa.Column('empathy_score', sa.FLOAT(), nullable=True),
    sa.Column('csi_score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_analyses_id'), 'daily_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_daily_analyses_csi_score'), 'daily_analyses', ['csi_score'], unique=False)
    op.create_index(op.f('idx_conversation_date'), 'daily_analyses', ['conversation_id', 'analysis_date'], unique=1)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fb_chat_id', sa.VARCHAR(), nullable=False),
    sa.Column('total_messages', sa.INTEGER(), nullable=True),
    sa.Column('customer_messages', sa.INTEGER(), nullable=True),
    sa.Column('agent_messages', sa.INTEGER(), nullable=True),
    sa.Column('first_message_time', sa.DATETIME(), nullable=True),
    sa.Column('last_message_time', sa.DATETIME(), nullable=True),
    sa.Column('common_topics', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_fb_chat_id'), 'conversations', ['fb_chat_id'], unique=1)
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('upload_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_upload_id'), 'jobs', ['upload_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###
