"""Add interaction statistics fields

Revision ID: 6763666040d9
Revises: 8bf74b604f56
Create Date: 2025-09-16 22:46:54.936988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6763666040d9'
down_revision: Union[str, Sequence[str], None] = '8bf74b604f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_analyses', sa.Column('interaction_duration', sa.Float(), nullable=True))
    op.add_column('interaction_analyses', sa.Column('interaction_complexity', sa.String(), nullable=True))
    op.add_column('interaction_analyses', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('interaction_analyses', sa.Column('turns_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_analyses', 'turns_count')
    op.drop_column('interaction_analyses', 'message_count')
    op.drop_column('interaction_analyses', 'interaction_complexity')
    op.drop_column('interaction_analyses', 'interaction_duration')
    # ### end Alembic commands ###
