"""Add InteractionAnalysis model for interaction-based CSI analysis

Revision ID: 8bf74b604f56
Revises: 557845a304fd
Create Date: 2025-09-16 22:00:40.199414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf74b604f56'
down_revision: Union[str, Sequence[str], None] = '557845a304fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('start_message_id', sa.Integer(), nullable=False),
    sa.Column('end_message_id', sa.Integer(), nullable=False),
    sa.Column('interaction_start', sa.DateTime(), nullable=False),
    sa.Column('interaction_end', sa.DateTime(), nullable=False),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('boundary_method', sa.String(), nullable=False),
    sa.Column('boundary_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_shift', sa.Float(), nullable=True),
    sa.Column('resolution_achieved', sa.Float(), nullable=True),
    sa.Column('fcr_score', sa.Float(), nullable=True),
    sa.Column('ces', sa.Float(), nullable=True),
    sa.Column('common_topics', sa.JSON(), nullable=True),
    sa.Column('first_response_time', sa.Float(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('total_handling_time', sa.Float(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('effort_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('empathy_score', sa.Float(), nullable=True),
    sa.Column('csi_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boundary_method', 'interaction_analyses', ['boundary_method'], unique=False)
    op.create_index('idx_conversation_interaction_start', 'interaction_analyses', ['conversation_id', 'interaction_start'], unique=False)
    op.create_index('idx_interaction_message_range', 'interaction_analyses', ['start_message_id', 'end_message_id'], unique=False)
    op.create_index(op.f('ix_interaction_analyses_csi_score'), 'interaction_analyses', ['csi_score'], unique=False)
    op.create_index(op.f('ix_interaction_analyses_id'), 'interaction_analyses', ['id'], unique=False)
    op.create_table('job_interaction_analyses',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('interaction_analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_analysis_id'], ['interaction_analyses.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'interaction_analysis_id')
    )
    op.drop_table('progress_updates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_updates',
    sa.Column('upload_id', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('total_conversations', sa.INTEGER(), nullable=True),
    sa.Column('processed_conversations', sa.INTEGER(), nullable=True),
    sa.Column('progress_percentage', sa.FLOAT(), nullable=True),
    sa.Column('current_stage', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.drop_table('job_interaction_analyses')
    op.drop_index(op.f('ix_interaction_analyses_id'), table_name='interaction_analyses')
    op.drop_index(op.f('ix_interaction_analyses_csi_score'), table_name='interaction_analyses')
    op.drop_index('idx_interaction_message_range', table_name='interaction_analyses')
    op.drop_index('idx_conversation_interaction_start', table_name='interaction_analyses')
    op.drop_index('idx_boundary_method', table_name='interaction_analyses')
    op.drop_table('interaction_analyses')
    # ### end Alembic commands ###
