"""constitutional_compliance_enhancements

Revision ID: f3d0817f4c42
Revises: 39ace2b248eb
Create Date: 2025-09-18 08:49:48.911323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d0817f4c42'
down_revision: Union[str, Sequence[str], None] = '39ace2b248eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### All columns already exist in the database! ###
    # The constitutional compliance fields were already added outside of Alembic
    # This migration just needs to create the indexes
    pass  # All columns already exist
    # Skip altering id column type - SQLite doesn't support this easily
    # op.alter_column('jobs', 'id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    
    # Create indexes for constitutional compliance and performance
    op.create_index('idx_job_constitutional', 'jobs', ['constitutional_compliance_required', 'ai_supremacy_validated', 'dual_csi_validated'], unique=False)
    op.create_index('idx_job_performance', 'jobs', ['actual_processing_time', 'cost_optimization_achieved'], unique=False)
    op.create_index('idx_job_session_type', 'jobs', ['session_id', 'job_type'], unique=False)
    op.create_index('idx_job_status_priority', 'jobs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_priority'), 'jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_jobs_session_id'), 'jobs', ['session_id'], unique=False)
    
    # Skip foreign key constraint for now - might need to be done manually
    # op.create_foreign_key(None, 'jobs', 'upload_sessions', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_session_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_priority'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index('idx_job_status_priority', table_name='jobs')
    op.drop_index('idx_job_session_type', table_name='jobs')
    op.drop_index('idx_job_performance', table_name='jobs')
    op.drop_index('idx_job_constitutional', table_name='jobs')
    op.alter_column('jobs', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'cost_optimization_achieved')
    op.drop_column('jobs', 'cost_optimization_target')
    op.drop_column('jobs', 'actual_processing_time')
    op.drop_column('jobs', 'estimated_processing_time')
    op.drop_column('jobs', 'dual_csi_validated')
    op.drop_column('jobs', 'ai_supremacy_validated')
    op.drop_column('jobs', 'constitutional_compliance_required')
    op.drop_column('jobs', 'context')
    op.drop_column('jobs', 'payload')
    op.drop_column('jobs', 'priority')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'session_id')
    # ### end Alembic commands ###
